### PR TITLE
async: return a Deferred instead of an Ivar

### PR DESCRIPTION
**Pull request by mbacarella**
This fixes a bug that went undetected in the last PR #27

### CODE REVIEW

**Comment by mbacarella** [comment]
Actually, returning the full Ivar is too much functionality. The library only needs to bind on the promise, rather than have functionality to fulfill the promise. Pushed a fix here.

**Review by anmonteiro — APPROVED** [review]
Nice catch, and nice improvement! Thanks!

**Comment by mbacarella** [comment]
Hi @anmonteiro, anything blocking merging this?

**Comment by anmonteiro** [comment]
Just forgot about it. Thanks for the ping!

**Pull request merged**
